import bpy
from bpy.types import Node


# Global scope storage for registered panels
TGR_EXEC_SCOPES = {}

def get_cached_blender_icons():
    """Dynamic EnumProperty callback that displays all icons with visual previews"""
    items = bpy.types.UILayout.bl_rna.functions['label'].parameters['icon'].enum_items
    
    # Format: (identifier, label, description, icon_name, numeric_id)
    return [
        (item.identifier, item.name, item.description, item.identifier, idx)
        for idx, item in enumerate(items)
    ]

# Cached Blender icons
BLENDER_ICONS = get_cached_blender_icons()


class NodeTreeCompiler:
    """Compiler for TGR node trees to generate UI code"""

    def __init__(self, data_tree, layout_tree, armature):
        self.data_tree = data_tree
        self.layout_tree = layout_tree
        self.armature = armature
        try:
            self.panel_nodes = [node for node in self.layout_tree.nodes if node.bl_idname == "TGR_LY_ND_Panel"]
        except AttributeError:
            self.panel_nodes = []
        try:
            self.operator_nodes = [node for node in self.data_tree.nodes if node.bl_idname == "TGR_LY_ND_Operator"]
        except AttributeError:
            self.operator_nodes = []
        try:
            self.property_group_nodes = [node for node in self.data_tree.nodes if node.bl_idname == "TGR_LY_ND_PropertyGroup"]
        except AttributeError:
            self.property_group_nodes = []
        self.indent_level = 0
        self._generated_code = []

    @property
    def generated_code(self) -> str:
        return "\n".join(self._generated_code)

    def _indent(self) -> str:
        return "    " * self.indent_level

    def _new_line(self, line: str):
        self._generated_code.append(f"{self._indent()}{line}")

    def _set_boilerplate(self):
        """Set the boilerplate code for the generated script"""
        self._new_line("# This script is auto-generated by the Telergy Rigger UI Compiler")
        self._new_line("import bpy")
        self._new_line("from bpy.types import Panel, PropertyGroup")
        self._new_line("")
        self._new_line("")

    def _set_classes_to_register(self):
        """Set the classes to register in the generated script"""
        self._new_line("# Add all the classes to register here:")
        self._new_line("CLASSES = [")
        self.indent_level += 1
        self._new_line("#Property Groups")
        for node in self.property_group_nodes:
            self._new_line(f"TGR_PG_{node.name.replace(' ', '_')},")
        self._new_line("#Operators")
        for node in self.operator_nodes:
            self._new_line(f"TGR_OT_{node.name.replace(' ', '_')},")
        self._new_line("#Panels")
        for node in self.panel_nodes:
            self._new_line(f"TGR_PT_{node.name.replace(' ', '_')},")
        self.indent_level -= 1
        self._new_line("]")

    def _value_node_string_get(self, value_node: Node) -> str:
        """Compile value nodes into Python code"""
        match value_node.bl_idname:
            case 'TGR_LY_ND_Value':
                return f"{value_node.value}"
            case 'TGR_LY_ND_CustomProp':
                if value_node.target.type != 'ARMATURE':
                    return f"bpy.data.objects['{value_node.target.name}']['{value_node.property_name}']"
                else:
                    return f"bpy.data.objects['{value_node.target.name}'].pose.bones['{value_node.subtarget}']['{value_node.property_name}']"
            case 'TGR_LY_ND_Prop':
                pass
            case _:
                # TODO: Show the connection is not valid
                pass

    def _compile_compare_node(self, compare_node: Node, parent_layout, level=0):
        """Compile compare nodes into Python code"""
        try:
            value_a = self._value_node_string_get(compare_node.inputs[0].links[0].from_node)
            value_b = self._value_node_string_get(compare_node.inputs[1].links[0].from_node)
        except IndexError:
            print("[TGR COMPILE COMPARE] Both input nodes must be connected")
            return
        condition = ""
        match compare_node.operation:
            case 'EQUAL':
                condition = f"{value_a} == {value_b}"
                pass
            case 'NOT_EQUAL':
                condition = f"{value_a} != {value_b}"
                pass
            case 'LESS':
                condition = f"{value_a} < {value_b}"
                pass
            case 'GREATER':
                condition = f"{value_a} > {value_b}"
                pass
            case 'LESS_EQUAL':
                condition = f"{value_a} <= {value_b}"
                pass
            case 'GREATER_EQUAL':
                condition = f"{value_a} >= {value_b}"
                pass
            case 'EXPRESSION':
                if not (compare_node.inputs[0].is_linked or compare_node.inputs[1].is_linked):
                    # TODO: Both sockets must be linked
                    pass
                condition = f"{compare_node.expression}"
                condition = condition.replace('A', value_a)
                condition = condition.replace('B', value_b)
        self._new_line(f"if {condition}:")
        self.indent_level += 1
        

    def _compile_if(self, if_node: Node, parent_layout, level=0):
        """Compile if nodes into Python code"""
        true_node = if_node.inputs[1].links[0].from_node if if_node.inputs[1].is_linked else None
        false_node = if_node.inputs[2].links[0].from_node if if_node.inputs[2].is_linked else None
        if if_node.inputs[0].is_linked:
            condition_node = if_node.inputs[0].links[0].from_node
            if condition_node.bl_idname == 'TGR_FC_ND_Compare':
                self._compile_compare_node(condition_node, parent_layout, level)
                self._compile_layout_nodes(layout_node=true_node, parent_layout=parent_layout, level=level)
                self.indent_level -= 1
                self._new_line("else:")
                self.indent_level += 1
                self._compile_layout_nodes(layout_node=false_node, parent_layout=parent_layout, level=level)
                self.indent_level -= 1
            elif condition_node.bl_idname == 'TGR_LY_ND_BoneCollection':
                vis_condition = ""
                solo_condition = ""
                if condition_node.use_visibility:
                    vis_condition = f"armature.collections_all['{condition_node.collection_name}'].is_visible"
                if condition_node.use_solo:
                    solo_condition = f"armature.collections_all['{condition_node.collection_name}'].is_solo"

                if vis_condition and not solo_condition:
                    condition = vis_condition
                elif solo_condition and not vis_condition:
                    condtion = solo_condition
                elif vis_condition and solo_condition:
                    condition = f"{vis_condition} and {solo_condition}"
                self._new_line(f"if {condition}:")
                self.indent_level += 1
                if true_node and true_node.bl_idname != 'TGR_LY_ND_Empty':
                    self._compile_layout_nodes(layout_node=true_node, parent_layout=parent_layout, level=level)
                else:
                    self._new_line("pass")
                self.indent_level -= 1
                self._new_line("else:")
                self.indent_level += 1
                if false_node and false_node.bl_idname != 'TGR_LY_ND_Empty':
                    self._compile_layout_nodes(layout_node=false_node, parent_layout=parent_layout, level=level)
                else:
                    self._new_line("pass")
                self.indent_level -= 1

        else:
            if if_node.inputs[0].default_value:
                if not true_node:
                    return
                match true_node.outputs[0].bl_idname:
                    case 'TGR_SKT_Layout':
                        self._compile_layout_nodes(true_node, parent_layout, level)
            else:
                if not false_node:
                    return
                match false_node.outputs[0].bl_idname:
                    case 'TGR_SKT_Layout':
                        self._compile_layout_nodes(false_node, parent_layout, level)

    def _compile_property_groups(self):
        """Compile property group nodes into Python code"""

    def _compile_operators(self):
        """Compile operator nodes into Python code"""

    def _compile_layout_nodes(self, layout_node: Node, parent_layout, level=0):
        """Compile layout nodes into Python code"""
        if not layout_node:
            return
        match layout_node.bl_idname:
            case "TGR_LY_ND_Row":
                self._compile_row(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_LY_ND_Column":
                self._compile_column(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_LY_ND_BoneCollection":
                self._compile_bone_collection(layout_node, parent_layout=parent_layout, visibility=layout_node.use_visibility, solo=layout_node.use_solo)
            case "TGR_LY_ND_Separator":
                self._compile_separator(layout_node, parent_layout=parent_layout)
            case "TGR_LY_ND_Label":
                self._compile_label(layout_node, parent_layout=parent_layout)
            case "TGR_LY_ND_CustomProp":
                self._compile_custom_prop(layout_node, parent_layout=parent_layout)
            case "TGR_LY_ND_Box":
                self._compile_box(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_FC_ND_If":
                self._compile_if(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_LY_ND_Split":
                self._compile_split(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_LY_ND_Grid":
                self._compile_grid(layout_node, parent_layout=parent_layout, level=level)

    def _compile_row(self, row_node: Node, parent_layout, level=0):
        """Compile row nodes into Python code"""
        self._new_line(f"row_{level} = {parent_layout}.row(align={row_node.align})")
        if row_node.height > 0:
            self._new_line(f"row_{level}.scale_y = {row_node.height}")
        for input_socket in row_node.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout=f"row_{level}", level=level + 1)

    def _compile_bone_collection(self, bone_collection_node: Node, parent_layout, visibility=True, solo=False):
        """Compile bone collection nodes into Python code"""
        if visibility:
            self._new_line(f"{parent_layout}.prop(armature.collections_all['{bone_collection_node.collection_name}'], 'is_visible', text='{bone_collection_node.collection_name}', toggle=True)")
        if solo:
            self._new_line(f"{parent_layout}.prop(armature.collections_all['{bone_collection_node.collection_name}'],"
                           f" 'is_solo', text='', toggle=True, icon='SOLO_ON' if armature.collections_all['{bone_collection_node.collection_name}'].is_solo else 'SOLO_OFF')")

    def _compile_separator(self, separator_node: Node, parent_layout):
        """Compile separator nodes into Python code"""
        self._new_line(f"{parent_layout}.separator()")
    
    def _compile_label(self, label_node: Node, parent_layout):
        """Compile label nodes into Python code"""
        icon_code = ""
        if label_node.use_icon:
            icon_code = f", icon='{label_node.icon}'"
        if label_node.inputs[0].is_linked and label_node.inputs[0].links[0].from_node.bl_idname == "TGR_DT_ND_String":
            input_node = label_node.inputs[0].links[0].from_node
            self._new_line(f"{parent_layout}.label(text='{input_node.text}'{icon_code})")
        else:
            text = label_node.inputs[0].default_value
            self._new_line(f"{parent_layout}.label(text='{text}'{icon_code})")

    def _compile_custom_prop(self, custom_prop_node: Node, parent_layout):
        """Compile custom property nodes into Python code"""
        if custom_prop_node.target.type == 'ARMATURE' and custom_prop_node.subtarget:
            text = custom_prop_node.alias if custom_prop_node.alias else custom_prop_node.property_name
            self._new_line(f"{parent_layout}.prop(bpy.data.objects['{custom_prop_node.target.name}'].pose.bones['{custom_prop_node.subtarget}'], "
                           f"'[\"{custom_prop_node.property_name}\"]', text='{text}'"
                           f"{", slider=True" if custom_prop_node.use_slider else ""}"
                           ")")
        else:
            self._new_line(f"{parent_layout}.prop(bpy.data.objects['{custom_prop_node.target.name}'], '[\"{custom_prop_node.property_name}\"]', text='{text}')")

    def _compile_column(self, column_node: Node, parent_layout, level=0):
        """Compile column nodes into Python code"""
        self._new_line(f"col_{level} = {parent_layout}.column(align={column_node.align})")
        if column_node.height > 0:
            self._new_line(f"col_{level}.scale_y = {column_node.height}")
        for input_socket in column_node.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout=f"col_{level}", level=level + 1)

    def _compile_box(self, box_node: Node, parent_layout, level=0):
        """Compile box nodes into Python code"""
        self._new_line(f"box_{level} = {parent_layout}.box()")
        for input_socket in box_node.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout=f"box_{level}", level=level + 1)

    def _compile_grid(self, grid_node: Node, parent_layout, level=0):
        """Compile grid nodes into Python code"""
        self._new_line(f"grid_{level} = {parent_layout}.grid_flow(columns={grid_node.columns}, even_columns={grid_node.even_columns}, align={grid_node.align})")
        for input_socket in grid_node.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout=f"grid_{level}", level=level + 1)

    def _compile_split(self, split_node: Node, parent_layout, level=0):
        """Compile split nodes into Python code"""
        if not (split_node.inputs[0].is_linked or split_node.inputs[1].is_linked):
            print("[TGR COMPILE SPLIT] Both input nodes must be connected")
            return
        left_node = split_node.inputs[0].links[0].from_node
        right_node = split_node.inputs[1].links[0].from_node
        self._new_line(f"split_{level} = {parent_layout}.split(factor={split_node.factor})")
        self._new_line(f"split_{level}_left = split_{level}.column()")
        self._new_line(f"split_{level}_right = split_{level}.column()")
        self._compile_layout_nodes(left_node, parent_layout=f"split_{level}_left", level=level)
        self._compile_layout_nodes(right_node, parent_layout=f"split_{level}_right", level=level)

    def _compile_layout(self, panel: Node):
        """Compile layout nodes into Python code"""
        self._new_line("def draw(self, context):")
        self.indent_level += 1
        self._new_line("layout = self.layout")
        self._new_line(f"armature = bpy.data.objects['{self.armature.name}'].data")
        self._new_line("")

        for input_socket in panel.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout="layout", level=0)

        self.indent_level -= 1

    def _compile_panels(self):
        """Compile panel nodes into Python code"""

        # Simplified version for fast iteration. In a full implementation, this would handle layout nodes and their properties.
        for panel in self.panel_nodes:
            self._new_line(f"class TGR_PT_{panel.name.replace(' ', '_')}(Panel):")
            self.indent_level += 1
            self._new_line(f"bl_label = '{panel.name}'")
            self._new_line(f"bl_idname = 'TGR_PT_{panel.name.replace(' ', '_')}'")
            self._new_line(f"bl_space_type = 'VIEW_3D'")
            self._new_line(f"bl_region_type = 'UI'")
            self._new_line(f"bl_category = '{self.layout_tree.name}'")
            if panel.parent != 'NONE':
                self._new_line(f"bl_parent_id = 'TGR_PT_{panel.parent.replace(' ', '_')}'")
            self._new_line("")
            self._compile_layout(panel)
            self.indent_level -= 1
            self._new_line("")
            self._new_line("")

    def _register_classes(self):
        """Generate the register function for the generated classes"""
        self._new_line("def register():")
        self.indent_level += 1
        self._new_line("for cls in CLASSES:")
        self.indent_level += 1
        self._new_line("bpy.utils.register_class(cls)")
        self.indent_level -= 2
        self._new_line("")
        self._new_line("")

    def _unregister_classes(self):
        """Generate the unregister function for the generated classes"""

        self._new_line("def unregister():")
        self.indent_level += 1
        self._new_line("for cls in CLASSES:")
        self.indent_level += 1
        self._new_line("bpy.utils.unregister_class(cls)")
        self.indent_level -= 2
        self._new_line("")
        self._new_line("")

    def _main(self):
        """Generate the main execution block for the script"""
        self._new_line("if __name__ == '__main__':")
        self.indent_level += 1
        self._new_line("register()")
        self.indent_level -= 1

    def compile(self):
        """Compile the node trees into a Python script"""
        self._set_boilerplate()
        self._compile_property_groups()
        self._compile_panels()
        self._set_classes_to_register()
        self._register_classes()
        self._unregister_classes()
        self._main()
        return self.generated_code


def run_tgr_ui_generator(armature=None):
    """Standalone compilation logic. Can be called directly from anywhere"""
    # Fallback to get active armature if none is passed
    if armature is None:
        if bpy.context.active_object and bpy.context.active_object.type == 'ARMATURE':
            armature = bpy.context.active_object
        else:
            selected_armatures = [o for o in bpy.context.selected_objects if o.type == 'ARMATURE']
            if selected_armatures:
                armature = selected_armatures[0]

    if not armature:
        print("[TGR Auto-Compile]: No active or selected Armature found.")
        return False

    layout_trees = [tree for tree in bpy.data.node_groups if tree.bl_idname == "TGR_NT_UI"]
    data_trees = [tree for tree in bpy.data.node_groups if tree.bl_idname == "TGR_NT_Data"]

    if not layout_trees:
        print("[TGR Auto-Compile]: No UI Layout tree found.")
        return False

    layout_tree = layout_trees[0]
    data_tree = data_trees[0] if data_trees else None
    
    script_name = f"{layout_tree.name.replace(' ', '_').lower()}.py"
    if script_name in bpy.data.texts:
        text_block = bpy.data.texts[script_name]
        text_block.clear()
    else:
        text_block = bpy.data.texts.new(script_name)

    text_block.use_module = True

    # 1. Compile Code
    compiler = NodeTreeCompiler(data_tree, layout_tree, armature)
    generated_code = compiler.compile()
    text_block.write(generated_code)


    # 2. Execute Code
    exec_globals = {
        "__name__": "__tgr_runtime__",
        "__file__": script_name,
        "__builtins__": __builtins__,
    }

    try:
        # Teardown previous classes
        old_globals = TGR_EXEC_SCOPES.get(script_name)
        if old_globals and "unregister" in old_globals:
            try:
                old_globals["unregister"]()
            except Exception:
                pass

        # Execute new script string
        exec(text_block.as_string(), exec_globals)
        TGR_EXEC_SCOPES[script_name] = exec_globals

        # Register classes
        if "register" in exec_globals:
            exec_globals["register"]()

        # Tag 3D Viewport for redraw
        if bpy.context.window_manager:
            for window in bpy.context.window_manager.windows:
                for area in window.screen.areas:
                    if area.type == 'VIEW_3D':
                        area.tag_redraw()

        return True

    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"[TGR Auto-Compile Error]: Execution failed: {e}")
        return False
