import bpy
from bpy.types import Node
from dataclasses import dataclass, field


class TGR_OT_UIPicker(bpy.types.Operator):
    """Hover over any UI area to detect the area and region. Click to select it"""

    bl_idname = "tgr.ui_picker"
    bl_label = "UI Picker"
    bl_options = {'REGISTER', 'UNDO'}
    
    def modal(self, context, event):
        # Cancel on right click or escape
        if event.type in {'RIGHTMOUSE', 'ESC'}:
            context.window.cursor_set('DEFAULT')
            context.workspace.status_text_set(None)
            return {'CANCELLED'}
        
        # Logic to detect UI area under mouse cursor
        found_area = None
        found_region = None
        
        for area in context.window.screen.areas:
            for region in area.regions:
                if (region.x <= event.mouse_x <= region.x + region.width and
                    region.y <= event.mouse_y <= region.y + region.height):
                    found_area = area
                    found_region = region
                    break
            if found_area:
                break
        
        # Update status text while hovering
        if event.type == 'MOUSEMOVE':
            if found_area and found_region:
                context.workspace.status_text_set(f"Area: {found_area.type}, Region: {found_region.type}")
            else:
                context.workspace.status_text_set("Hover over a UI area...")
        
        # Confirm selection on left click
        if event.type == 'LEFTMOUSE' and event.value == 'PRESS':
            if found_area and found_region:
                self.view_node.space_type = found_area.type
                self.view_node.region_type = found_region.type
                # Redraw the node editor to reflect changes
                for area in context.window.screen.areas:
                    if area.type == 'NODE_EDITOR':
                        area.tag_redraw()
                self.report({'INFO'}, f"Selected Area: {found_area.type}, Region: {found_region.type}")
            else:
                self.report({'WARNING'}, "No UI area detected under cursor")
            context.window.cursor_set('DEFAULT')
            context.workspace.status_text_set(None)
            return {'FINISHED'}
        
        return {'RUNNING_MODAL'}
    
    def invoke(self, context, event):
        self.view_node = context.active_node
        context.window.cursor_set('EYEDROPPER')
        context.window_manager.modal_handler_add(self)
        context.workspace.status_text_set("Hover over a UI area and click to select. Right click or Esc to cancel.")
        return {'RUNNING_MODAL'}


@dataclass
class TGR_Panel:
    """Data structure to hold panel information"""
    name: str
    category: str
    layout_inputs: list[Node] = field(default_factory=list)


@dataclass
class TGR_Row:
    """Data structure to hold row information"""
    aligned: bool = False
    height: int = 0
    parent: object = None
    layout_inputs: list[Node] = field(default_factory=list)


@dataclass
class TGR_Column:
    """Data structure to hold column information"""
    aligned: bool = False
    width: int = 0
    parent: object = None
    layout_inputs: list[Node] = field(default_factory=list)

@dataclass
class TGR_BoneCollection:
    """Data structure to hold bone collection information"""
    name: str
    use_visibility: bool = True
    use_solo: bool = False

class NodeTreeCompiler:
    """Compiler for TGR node trees to generate UI code"""

    def __init__(self, data_tree, layout_tree, armature):
        self.data_tree = data_tree
        self.layout_tree = layout_tree
        self.armature = armature
        self.panel_nodes = [node for node in self.layout_tree.nodes if node.bl_idname == "TGR_LY_ND_Panel"]
        self.operator_nodes = [node for node in self.data_tree.nodes if node.bl_idname == "TGR_LY_ND_Operator"]
        self.property_group_nodes = [node for node in self.data_tree.nodes if node.bl_idname == "TGR_LY_ND_PropertyGroup"]
        self.indent_level = 0
        self._generated_code = []

    @property
    def generated_code(self) -> str:
        return "\n".join(self._generated_code)

    def _indent(self) -> str:
        return "    " * self.indent_level

    def _new_line(self, line: str):
        self._generated_code.append(f"{self._indent()}{line}")

    def _set_boilerplate(self):
        """Set the boilerplate code for the generated script"""
        self._new_line("# This script is auto-generated by the Telergy Rigger UI Compiler")
        self._new_line("import bpy")
        self._new_line("from bpy.types import Panel, PropertyGroup")
        self._new_line("")
        self._new_line("")

    def _set_classes_to_register(self):
        """Set the classes to register in the generated script"""
        self._new_line("")
        self._new_line("")
        self._new_line("# Add all the classes to register here:")
        self._new_line("CLASSES = [")
        self.indent_level += 1
        self._new_line("#Property Groups")
        for node in self.property_group_nodes:
            self._new_line(f"TGR_PG_{node.name.replace(' ', '_')},")
        self._new_line("#Operators")
        for node in self.operator_nodes:
            self._new_line(f"TGR_OT_{node.name.replace(' ', '_')},")
        self._new_line("#Panels")
        for node in self.panel_nodes:
            self._new_line(f"TGR_PT_{node.name.replace(' ', '_')},")
        self.indent_level -= 1
        self._new_line("]")

    def _compile_compare_node(self, compare_node: Node, parent_layout, level=0):
        """Compile compare nodes into Python code"""
        

    def _compile_if(self, if_node: Node, parent_layout, level=0):
        """Compile if nodes into Python code"""
        if if_node.inputs[0].is_linked:
            condition_node = if_node.inputs[0].links[0].from_node
            if not condition_node.bl_idname == 'TGR_FC_ND_Compare':
                # TODO: Show warning
                pass
            else:
                self._compile_compare_node(condition_node, parent_layout, level)
        else:
            if if_node.inputs[0].default_value:
                true_node = if_node.inputs[1].links[0].from_node
                match true_node.outputs[0].bl_idname:
                    case 'TGR_SKT_Layout':
                        self._compile_layout_nodes(true_node, parent_layout, level)
            else:
                false_node = if_node.inputs[2].links[0].from_node
                match false_node.outputs[0].bl_idname:
                    case 'TGR_SKT_Layout':
                        self._compile_layout_nodes(false_node, parent_layout, level)

    def _compile_property_groups(self):
        """Compile property group nodes into Python code"""

    def _compile_operators(self):
        """Compile operator nodes into Python code"""

    def _compile_layout_nodes(self, layout_node: Node, parent_layout, level=0):
        """Compile layout nodes into Python code"""
        match layout_node.bl_idname:
            case "TGR_LY_ND_Row":
                self._compile_row(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_LY_ND_Column":
                self._compile_column(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_LY_ND_BoneCollection":
                self._compile_bone_collection(layout_node, parent_layout=parent_layout, visibility=layout_node.use_visibility, solo=layout_node.use_solo)
            case "TGR_LY_ND_Separator":
                self._compile_separator(layout_node, parent_layout=parent_layout)
            case "TGR_LY_ND_Label":
                self._compile_label(layout_node, parent_layout=parent_layout)
            case "TGR_LY_ND_CustomProp":
                self._compile_custom_prop(layout_node, parent_layout=parent_layout)
            case "TGR_LY_ND_Box":
                self._compile_box(layout_node, parent_layout=parent_layout, level=level)
            case "TGR_FC_ND_If":
                self._compile_if(layout_node, parent_layout=parent_layout, level=level)

    def _compile_row(self, row_node: Node, parent_layout, level=0):
        """Compile row nodes into Python code"""
        self._new_line(f"row_{level} = {parent_layout}.row(align={row_node.align})")
        if row_node.height > 0:
            self._new_line(f"row_{level}.scale_y = {row_node.height}")
        for input_socket in row_node.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout=f"row_{level}", level=level + 1)

    def _compile_bone_collection(self, bone_collection_node: Node, parent_layout, visibility=True, solo=False):
        """Compile bone collection nodes into Python code"""
        if visibility:
            self._new_line(f"{parent_layout}.prop(armature.collections_all['{bone_collection_node.collection_name}'], 'is_visible', text='{bone_collection_node.collection_name}', toggle=True)")
        if solo:
            self._new_line(f"{parent_layout}.prop(armature.collections_all['{bone_collection_node.collection_name}'],"
                           f" 'is_solo', text='', toggle=True, icon='SOLO_ON' if armature.collections_all['{bone_collection_node.collection_name}'].is_solo else 'SOLO_OFF')")

    def _compile_separator(self, separator_node: Node, parent_layout):
        """Compile separator nodes into Python code"""
        self._new_line(f"{parent_layout}.separator()")
    
    def _compile_label(self, label_node: Node, parent_layout):
        """Compile label nodes into Python code"""
        if label_node.inputs[0].is_linked and label_node.inputs[0].links[0].from_node.bl_idname == "TGR_DT_ND_String":
            input_node = label_node.inputs[0].links[0].from_node
            self._new_line(f"{parent_layout}.label(text='{input_node.text}')")
        else:
            text = label_node.inputs[0].default_value
            self._new_line(f"{parent_layout}.label(text='{text}')")

    def _compile_custom_prop(self, custom_prop_node: Node, parent_layout):
        """Compile custom property nodes into Python code"""
        if custom_prop_node.target.type == 'ARMATURE' and custom_prop_node.subtarget:
            text = custom_prop_node.alias if custom_prop_node.alias else custom_prop_node.property_name
            self._new_line(f"{parent_layout}.prop(bpy.data.objects['{custom_prop_node.target.name}'].pose.bones['{custom_prop_node.subtarget}'], '[\"{custom_prop_node.property_name}\"]', text='{text}')")
        else:
            self._new_line(f"{parent_layout}.prop(bpy.data.objects['{custom_prop_node.target.name}'], '[\"{custom_prop_node.property_name}\"]', text='{text}')")

    def _compile_column(self, column_node: Node, parent_layout, level=0):
        """Compile column nodes into Python code"""
        self._new_line(f"col_{level} = {parent_layout}.column(align={column_node.align})")
        if column_node.height > 0:
            self._new_line(f"col_{level}.scale_y = {column_node.height}")
        for input_socket in column_node.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout=f"col_{level}", level=level + 1)

    def _compile_box(self, box_node: Node, parent_layout, level=0):
        """Compile box nodes into Python code"""
        self._new_line(f"box_{level} = {parent_layout}.box()")
        for input_socket in box_node.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout=f"box_{level}", level=level + 1)

    def _compile_layout(self, panel: Node):
        """Compile layout nodes into Python code"""
        self._new_line("def draw(self, context):")
        self.indent_level += 1
        self._new_line("layout = self.layout")
        self._new_line(f"armature = bpy.data.objects['{self.armature.name}'].data")
        self._new_line("")

        for input_socket in panel.inputs:
            if input_socket.is_linked:
                input_node = input_socket.links[0].from_node
                self._compile_layout_nodes(input_node, parent_layout="layout", level=0)

        self.indent_level -= 1

    def _compile_panels(self):
        """Compile panel nodes into Python code"""

        # Simplified version for fast iteration. In a full implementation, this would handle layout nodes and their properties.
        for panel in self.panel_nodes:
            self._new_line(f"class TGR_PT_{panel.name.replace(' ', '_')}(Panel):")
            self.indent_level += 1
            self._new_line(f"bl_label = '{panel.name}'")
            self._new_line(f"bl_idname = 'TGR_PT_{panel.name.replace(' ', '_')}'")
            self._new_line(f"bl_space_type = 'VIEW_3D'")
            self._new_line(f"bl_region_type = 'UI'")
            self._new_line(f"bl_category = '{self.layout_tree.name}'")
            if panel.parent != 'NONE':
                self._new_line(f"bl_parent_id = 'TGR_PT_{panel.parent.replace(' ', '_')}'")
            self._new_line("")
            self._compile_layout(panel)
            self.indent_level -= 1
            self._new_line("")
            self._new_line("")

    def _register_classes(self):
        """Generate the register function for the generated classes"""
        self._new_line("def register():")
        self.indent_level += 1
        self._new_line("for cls in CLASSES:")
        self.indent_level += 1
        self._new_line("bpy.utils.register_class(cls)")
        self.indent_level -= 2
        self._new_line("")
        self._new_line("")

    def _unregister_classes(self):
        """Generate the unregister function for the generated classes"""

        self._new_line("def unregister():")
        self.indent_level += 1
        self._new_line("for cls in CLASSES:")
        self.indent_level += 1
        self._new_line("bpy.utils.unregister_class(cls)")
        self.indent_level -= 2
        self._new_line("")
        self._new_line("")

    def _main(self):
        """Generate the main execution block for the script"""
        self._new_line("if __name__ == '__main__':")
        self.indent_level += 1
        self._new_line("register()")
        self.indent_level -= 1

    def compile(self):
        """Compile the node trees into a Python script"""
        self._set_boilerplate()
        self._compile_property_groups()
        self._compile_panels()
        self._set_classes_to_register()
        self._register_classes()
        self._unregister_classes()
        self._main()
        return self.generated_code


class TGR_OT_GenerateUI(bpy.types.Operator):
    """Generate the UI python script"""

    bl_idname = "tgr.generate_ui"
    bl_label = "Generate UI"
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        if context.active_object is None or context.space_data is None:
            return False
        return context.active_object.type == 'ARMATURE'

    def execute(self, context):
        layout_tree = [tree for tree in bpy.data.node_groups if tree.bl_idname == "TGR_NT_UI"]
        data_tree = [tree for tree in bpy.data.node_groups if tree.bl_idname == "TGR_NT_Data"]
        armature = context.active_object
        
        if not layout_tree:
            self.report({'ERROR'}, "No active layout node tree found")
            return {"CANCELLED"}

        layout_tree = layout_tree[0]  # Get the first matching node tree
        data_tree = data_tree[0] if data_tree else None  # Get the first matching data node tree, if any
        print("Compiling UI script:", layout_tree.name, "for armature:", armature.name)
        
        # Create or overwrite the text block for the UI script
        script_name = f"{layout_tree.name.replace(' ', '_').lower()}.py"
        if script_name in bpy.data.texts:
            text_block = bpy.data.texts[script_name]
            text_block.clear()
        else:
            text_block = bpy.data.texts.new(script_name)
        
        # Compile the node tree

        compiler = NodeTreeCompiler(data_tree, layout_tree, armature)
        generated_code = compiler.compile()

        # Write the generated code to the text block
        text_block.write(generated_code)
        
        # Execute the generated script
        try:
            exec(text_block.as_string())
            self.report({'INFO'}, f"UI script '{script_name}' compiled and executed successfully.")
        except Exception as e:
            self.report({'ERROR'}, f"Error executing compiled UI script: {e}")
        
        return {"FINISHED"}


class TGR_OT_CreateExecutable(bpy.types.Operator):
    """Create a new operator entry and execute function on the tgr_operators.py text block"""
    
    bl_idname = "tgr.create_executable"
    bl_label = "Create Executable"
    bl_options = {'REGISTER', 'UNDO'}
    
    name: bpy.props.StringProperty(name="Operator Name", default="")
    exec_type: bpy.props.StringProperty(name="Executable Type", default="OPERATOR")

    def execute(self, context):
        if not self.name.strip():
            self.report({'ERROR'}, "Operator name cannot be empty")
            return {'CANCELLED'}
        
        if not self.exec_type in ["OPERATOR", "CALLBACK"]:
            self.report({'ERROR'}, "Executable type must be either 'OPERATOR' or 'CALLBACK'")
            return {'CANCELLED'}
        
        text_block_name = "tgr_executables.py"
        if text_block_name not in bpy.data.texts:
            text_block = bpy.data.texts.new(text_block_name)
            text_block.write("# This is the tgr_executables.py text block. It contains executable definitions for Telergy Rigger.\n\n")
        else:
            text_block = bpy.data.texts[text_block_name]

        # Generate a unique executable name
        executable_name = ""
        if self.exec_type == "OPERATOR":
            executable_name = f"TGR_OT_{self.name.capitalize().replace(' ', '_')}"
        elif self.exec_type == "CALLBACK":
            executable_name = f"tgr_{self.name.lower().replace(' ', '_')}"
            
        if f"{self.exec_type}: {self.name}" in text_block.as_string():
            self.report({'ERROR'}, f"An executable with the same name '{self.name}' and type '{self.exec_type}' already exists.")
            return {'CANCELLED'}
        
        # Create the operator execute function template
        executable_code = f"""
# {self.exec_type}: {self.name}
def {"execute_" + executable_name if self.exec_type == "OPERATOR" else executable_name}({"self, context" if self.exec_type == "OPERATOR" else ""}):
    # TODO: Implement the functionality for this {self.exec_type.lower()}
    return {{'FINISHED'}}\n
"""
     
        text_block.write(executable_code)
        
        # Find a text editor area to display the new executable code
        for area in context.window.screen.areas:
            if area.type == 'TEXT_EDITOR':
                area.spaces.active.text = text_block
                break
        
        return {'FINISHED'}
